# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:  [push]
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    # -v : パッケージ名を出力
    - name: Build
      run: go build -v ./...
      working-directory: app/.

    # -v : テスト成功しても値を出力
    - name: Test
      run: go test -v ./...
      working-directory: app/.

